### ISSUE TITLE
Define 'mobile-first'

### ISSUE THREAD

**Issue by mrmrs** [cardinalcss/cardinalcss#74]
The inclusion of max-width based media queries seems to violate the concepts behind mobile-first css architecture. I'm curious as to how this architecture is considered to be mobile-first?

**Comment by cbracco** [comment]
Hi @mrmrs,

The only max-width based media queries included in Cardinal are [mixins](https://github.com/cbracco/cardinal/blob/master/base/mixins/media-queries.less#L19). They are not used by the project’s architecture. For instance, utilities use the [`.screens()` mixin](https://github.com/cbracco/cardinal/blob/master/base/mixins/media-queries.less#L123), which chains together a bunch of min-width based media queries. 

These max-width mixins are available to the developer as a tool to use in *exceptional* circumstances, not to be used as the default approach (mobile-first is always the default). I should probably state this in the [`/base` subdirectory README](https://github.com/cbracco/cardinal/tree/master/base#media-queries) as well.

By including them, but not using them, do you still feel this violates the concepts of a mobile-first CSS architecture?

**Comment by mrmrs** [comment]
Well you say 'Cardinal is a modular, “mobile-first” CSS framework' - and you link to a talk where the definition of a framework is "a basic structure underlying a system, concept, or text." 

These mixins make up the basic underlying structure to me - so yes I view them as violating the construct of mobile-first architecture. Just my opinion so take it with a grain of salt. But seems like mobile-first is used more as a buzz-word with these included in the source.

**Comment by cbracco** [comment]
You make a good point! I appreciate your opinions. I’ll consider removing the mixins that do not adhere to the “mobile-first” methodology in the next release. Thanks, Adam.

**Comment by cbracco** [comment]
As of [3.3.0](https://github.com/cbracco/cardinal/releases/tag/3.3.0), there are no more max-width media query mixins. Thanks again for your feedback. Always appreciated.
