### ISSUE TITLE
Attribution

### ISSUE THREAD

**Issue by mrmrs** [cardinalcss/cardinalcss#75]
This css seems to copy/borrow **heavily** from existing toolkits and frameworks but I couldn't find any attribution anywhere. Maybe consider adding some.

**Comment by cbracco** [comment]
I cannot believe I neglected to do this, I am very embarrassed. I apologize to you and others who should be given credit as inspiration for this project as it has evolved.

As of [3.2.8](https://github.com/cbracco/cardinal/releases/tag/3.2.8), I’ve added specific attribution to the README file for the entire repo, and to the README file in the `/utilities` subdirectory.

There have always been [links in the code comments](https://github.com/cbracco/cardinal/search?utf8=%E2%9C%93&q=%22%40link%22) to serve as additional information about the code, as well as attribution. I added some more explicit attribution in the comments as well.

Thank you for calling me out.
