### ISSUE TITLE
Textarea height: auto !important prevents resize

### ISSUE THREAD

**Issue by michaek** [cardinalcss/cardinalcss#80]
In current Chrome, Safari and Firefox `height: auto !important` prevents the following `resize: vertical` from taking effect. Possibly just `height: auto` would be more forgiving?

The [official example](http://codepen.io/cbracco/pen/QbNbOM) shows the bug in action.

**Comment by cbracco** [comment]
Hi @michaek,

Appears you are correct! I have just pushed up a fix as of [3.4.1](https://github.com/cardinalcss/cardinalcss/releases/tag/3.4.1).

Good eye! Thanks for letting me know about this.
