### ISSUE TITLE
Remove Outline reset on Forms

### ISSUE THREAD

**Issue by Johnogram** [cardinalcss/cardinalcss#81]
Hi there,

I want to start off by saying, I love the cardinalcss framework! We use it on most of our projects now, and it is so easy to use, un-opinionated and lightweight.

Would you consider a pull request to remove the outline reset on forms. Currently, it makes it near impossible to over-ride the 

``` CSS
outline: 0 none;
```

without setting the property to solid, which looks ugly as hell.

Regards,

John

**Comment by cbracco** [comment]
@Johnogram thanks for bringing this up. I agree that using `outline: 0 none;` here is probably not appropriate. I will remove this.

**Comment by cbracco** [comment]
@Johnogram these styles have been removed as of [3.5.1](https://github.com/cardinalcss/cardinalcss/tree/3.5.1). Thanks for raising the issue!

**Comment by Johnogram** [comment]
Excellent! Thanks for acting on that so quickly.
