### ISSUE TITLE
Missing bracket @font-face in font-face mixin

### ISSUE THREAD

**Issue by FlexCarver** [cardinalcss/cardinalcss#85]
Hi there, I think you are missing the bracket @font-face in the font-face mixin, regards, FlexCarver

**Comment by cbracco** [comment]
@FlexCarver yes you are correct, nice catch! Can you tell I don’t use that much...? Haha. Fix incoming.

**Comment by cbracco** [comment]
@FlexCarver this has been fixed as of [3.6.1](https://github.com/cardinalcss/cardinalcss/releases/tag/3.6.1). Thanks for pointing it out!
