### ISSUE TITLE
Add more grid gutter classes

### ISSUE THREAD

**Issue by lukechilds** [cardinalcss/cardinalcss#86]
The grid gutter classes like `.gutter-2` are really useful, however it's a shame there are only classes for 0, 1/2, 1 and 2. I've been hacking in my own classes for `.gutter-3` - `.gutter-10`.

Just wondered if there was a reason you only go up to 2 and if not would you accept a pr to go to 10?

**Comment by cbracco** [comment]
@lukechilds the reason was to prevent too much bloat, anything past 3-4 multiples is probably superfluous for most users’ needs?

**Comment by lukechilds** [comment]
Fair enough, I'll keep mine separate.

**Comment by cbracco** [comment]
@lukechilds Okay, closing this one out for now. Thanks!
