### ISSUE TITLE
Consider changing font 

### ISSUE THREAD

**Issue by octamois** [cardinalcss/cardinalcss#92]
Historically this has been reported as duplicate / double monospace font at the time of writing 13 times, this issue is not about that, this is about actually removing it as Normalize should no longer require it:

Browsers using Blink, Gecko, and WebKit reduce the size of monospace. Therefore, the monospace,monospace fix applies to Android ≤ 6, Chrome ≤ 49, Firefox ≤ 45, iOS ≤ 9, Opera 15-35, and Safari 5-9. The fix does not work for Safari ≤ 4.
Browsers using Presto and Trident treat monospace normally. Therefore, the monospace,monospace fix is not required for Edge 12-13, Internet Explorer 8-11, Opera ≤ 12.15, and Windows Phone ≤ 8.1.
Based on browser usage here: https://caniuse.com/usage-table:

Android ≤ 6: 2.01% (This is based on ≤ 5, there's no data on v6 /shrug)
Chrome ≤ 49: 1.41%
Firefox ≤ 45: 0.43%
iOS ≤ 9: 0.09%
Opera 15-35: 0.27%
Safari 5-9: 0.23%
Browser usage that is affected by this issue is pretty low, what would the threshold be for this to be considered to no longer be required by Noormalize?

**Comment by cbracco** [comment]
thanks for the info! closing since this repo is no longer being actively maintained
